# Generated by Django 5.1.3 on 2024-12-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_manager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
