# Generated by Django 5.1.3 on 2024-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_app', '0004_alter_integration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(choices=[('VK', 'ВКонтакте'), ('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp')], max_length=255),
        ),
    ]
