# Generated by Django 5.1.3 on 2024-12-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('gpt', 'gpt'), ('manager', 'manager'), ('user', 'user'), ('admin', 'admin')], max_length=255),
        ),
    ]
