# Generated by Django 5.1.3 on 2024-12-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_message_sender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messanger_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
