# Generated by Django 5.1.3 on 2024-12-15 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_initial'),
        ('user_app', '0003_alter_manager_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='user_app.manager'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ManagerChat',
        ),
        migrations.DeleteModel(
            name='UserChat',
        ),
    ]
