# Generated by Django 5.1.3 on 2024-12-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chat_messanger_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('gpt', 'gpt'), ('manager', 'manager'), ('client', 'client'), ('admin', 'admin')], max_length=255),
        ),
    ]
