# Generated by Django 5.1.3 on 2024-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_alter_message_sender_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messanger_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
