# Generated by Django 5.1.3 on 2024-12-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatGPT_app', '0003_chatgpt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgpt',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
